### ISSUE TITLE
feat: members-db からの自動更新

### ISSUE THREAD

**Issue by MikuroXina** [approvers/site-data#1]
members-db が更新されたときに, `data/members/list.yaml` のデータを members-db-store から取得したデータで更新して反映させる.

また, この更新完了を approvers.github.io に通知する.

これにより, 以下の自動ワークフローを実現する.

1. members-db-store のデータを更新
2. site-data のデータを更新
3. approvers.github.io を再生成

実装手段を検討する必要アリ.

**Comment by siketyan** [comment]
members-db からイベント飛ばすのには反対だったりします（依存方向が逆転するので）

**Comment by mirror-kt** [comment]
GitHub Actionsのcronで定期的にmembers-dbの更新をfetchしにいくとか

**Comment by MikuroXina** [comment]
members-db の更新がなされなくなっているため, 一旦 Close します.
